/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.signer.service;

import java.security.spec.InvalidKeySpecException;

import org.json.JSONException;
import org.junit.Assert;
import org.junit.Test;

import com.signer.service.impl.JsonConfiguration;

public class JsonConfigurationTest {
	
    @Test 
    public void testValidConfig() throws Exception {
    	String configJson = "{\n" + 
    			"    \"port\" : 8080,\n" + 
    			"    \"jws_public_key\" : \"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmoM7w6SDrduzmC66AAq+5apOeFXoKr/sf3+NO0u9T2Cw2kPChGzDnUj9L2Rd87F/p9NlveyLYdzHGxJWd7okBosr/kTEq57pyYPuaPwPcfjmIUBxxECS0//DH8Wk+TV0mBBOC8P6sSZs5R/WxCk7Zy8DWnUeplI6v6vQ96yj96ZE8ZQOKTa0o7kvy9L7RxR52yuqUhwk35OJZjyI00DoGOR9F957WEWaqmwk++eOLE/KiZIkUT4YdRcTEGDmfGBOIvoi+XUlxyi1cDDfeNmg84dTClyEhgY7hqE6QqLz8NKVKtA6+spovqXxKNdZccyNKyUyiaqoeuIWAuz7hvuocQIDAQAB\"\n" + 
    			"}";
    	JsonConfiguration config = new JsonConfiguration(configJson);
    	Assert.assertEquals(8080, config.getPort());
    	Assert.assertEquals("X.509", config.getJwsKey().getFormat());
    }
    
    @Test (expected = JSONException.class)
    public void testInvalidPort() throws Exception {
    	String configJson = "{\n" + 
    			"    \"port\" : \"aaa\"\n" +
    			"}";
    	new JsonConfiguration(configJson);    	
    }
    
    @Test (expected = InvalidKeySpecException.class)
    public void testInvalidJwsKey() throws Exception {
    	String configJson = "{\n" + 
    			"    \"port\" : 8080,\n" + 
    			"    \"jws_public_key\" : \"MIIEvaaaaaaa\"\n" + 
    			"}";
    	new JsonConfiguration(configJson);    	
    }
}
